### ISSUE TITLE
OS X support.

### ISSUE THREAD

**Issue by leconteur** [tensorflow/fold#37]
I understand that you're not in a situation that enables you to provide support for mac. However, could we keep this issue open to keep track of the situation?

**Comment by moshelooks** [comment]
sgtm

**Comment by bionicles** [comment]
I would also like to use fold on macos.
How can we help fix this?

**Comment by jared-mess** [comment]
I'm not sure why fold crashes on OS X and not Ubuntu. Is this the same bug that everyone else on OS X is seeing?
``` Python
Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:25:17) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow_fold as td
python(28024,0x7fff79d53000) malloc: *** error for object 0x11213d678: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
Setting a breakpoint at `malloc_error_break` produces this backtrace:
``` shell
#0  0x00007fff8eb96f32 in malloc_error_break () from /usr/lib/system/libsystem_malloc.dylib
#1  0x00007fff8eb87fd2 in free () from /usr/lib/system/libsystem_malloc.dylib
#2  0x0000000118fa1aab in tensorflow::OpDef::SharedDtor() () from /Users/jared-mess/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_fold/loom/_deserializing_weaver_op.so
#3  0x0000000118fa18fc in tensorflow::OpDef::~OpDef() () from /Users/jared-mess/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_fold/loom/_deserializing_weaver_op.so
#4  0x0000000118f30fdd in _GLOBAL__sub_I_deserializing_weaver_op.cc () from /Users/jared-mess/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_fold/loom/_deserializing_weaver_op.so
```

**Comment by leconteur** [comment]
I have the same thing.

**Comment by jared-mess** [comment]
A quick search found that this bug is also reported in the deepmath repo with a few more details:
https://github.com/tensorflow/deepmath/issues/13
